# Generated by Django 5.2 on 2025-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetadata',
            name='token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
